# Generated by Django 4.2.3 on 2023-07-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='imagenArticulo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
