# Generated by Django 4.2.3 on 2023-08-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0003_alter_vendedor_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='articulo',
            field=models.CharField(choices=[('auto', 'Auto'), ('bicicletas', 'Bicicletas'), ('motos', 'Motos'), ('monopatines', 'Monopatines'), ('varios', 'Varios')], default='auto', max_length=15),
        ),
    ]
